### ISSUE TITLE
有个问题该不该问？

### ISSUE THREAD

**Issue by Lanseria** [Lellansin/node-scanf#10]
就是平时笔试算法题，用nodejs做，怎么写它才能通过？好似它的版本提供node -v 0.11的，大神有类似经验吗？谢谢啦 [列举一个牛客网的例子](https://www.nowcoder.com/test/question/done?tid=8841242&qid=44804#summary)

**Comment by Lellansin** [comment]
去刷 https://leetcode.com/ 吧

**Comment by Lanseria** [comment]
谢谢
