### ISSUE TITLE
Bug with Russian Language

### ISSUE THREAD

**Issue by nagayev** [Lellansin/node-scanf#14]
OS:Win10
Scanf version:latest from npm
Bug:
var scanf = require('scanf');
process.stdin.setEncoding('ascii');
console.log('Pleas input your name');
var name = scanf('%s');
console.log(name);
//should outputs ф,but ouputs �

**Comment by Artoria2e5** [comment]
ф is not a part of ASCII.

**Comment by nagayev** [comment]
@Artoria2e5 Oh, yes. Thanks.
