### ISSUE TITLE
输入特定中文时遇到问题

### ISSUE THREAD

**Issue by gzz2000** [Lellansin/node-scanf#15]
> scanf.sscanf('兴安盟 122.05 46.08', '%s%f%f')
[ '兴安', 122.05, 46.08 ]

可以看到少读了一个字

**Comment by Lellansin** [comment]
Fixed by https://github.com/Lellansin/node-scanf/commit/ac407d578892ade99deea2af19bdf858d1453a47#diff-9cf1a4b56e69527c337ebf459b8f8864R92. you could checkout new version 1.0.1 to fix it.

**Comment by gzz2000** [comment]
Great.
