### ISSUE TITLE
Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by thinkmoon** [Lellansin/node-scanf#16]
![image](https://user-images.githubusercontent.com/28600813/56023408-582ac980-5d40-11e9-8e96-9d7dddf3c342.png)

我在微信小程序里面引用的时候显示这个

**Comment by Lellansin** [comment]
你好，str 不能传 undefined，这个是 scanf a string，默认参数是 string 了（不是 undefined）。

**Comment by Lellansin** [comment]
Emm, 回头我加一个判断 undefined
