### ISSUE TITLE
Support for padding operation.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Lellansin/node-scanf#19]
Support for padding selector

Example: '%05d'

**Comment by Lellansin** [comment]
Could give me a test case about it? I mean I didn't know about that kind of format with *scanf*. And need some case to figure out.

**Comment by LiamKarlMitchell** [comment]
Comprehensive reading if interested.
https://wpollock.com/CPlus/PrintfRef.htm
https://en.wikipedia.org/wiki/Printf_format_string

A cpp example.
```cpp
int value;
sscanf("00015", "%05d", &value);
// value would be 15.
```

Test case?
```js
    it('[%d] \t\tshould handle Zero Pad', function(done) {
      var num = sscanf('00015', "%05d");
      should.strictEqual(num, 15);
      done();
    });
```


I'm trying to add this feature in, but got to a point where its a little tricky to pass more data through and work with it. I'm not convinced regex is the right approach here.

```js
// The syntax for a format placeholder is
// %[parameter][flags][width][.precision][length]type
// But this is not fully supported in this library yet.

var scanf = module.exports = function(format) {
  var re = new RegExp('[^%]*%(.[0-9]+)?[A-Za-z][^%]*', 'g'); // [^%]*%[A-Za-z][^%]*

//.....

var dealType = function(format) {
  var ret;
  var res = format.match(/%(?:(.)([0-9]+))?([A-Za-z]+)/);
  var res2 = format.match(/[^%]*/);
  if (!res) {
    return null;
  }

  var type = res[3];
  var pre = !!res2 ? res2[0] : null;
  var next = format.substr(format.indexOf(type) + type.length);
```

Might have to parse the format string, and build up a list of instructions to run against the input string to pull out the values.

There may be other features that are not implemented in this library as well.

**Comment by Lellansin** [comment]
I did some work about this issue, which you could check it on #21.
