### ISSUE TITLE
Parsing single character

### ISSUE THREAD

**Issue by trichner** [Lellansin/node-scanf#2]
Parsing a single character would be nice, e.g. `%c` :)

**Comment by Lellansin** [comment]
Welcome to talk about the function about parse more, I'm glad to improve this module. :)

**Comment by piranna** [comment]
Seems `%c` is not implemented, isn't it? I'm having the same problem and in the source code it seems it's not supported... It could be used `%s` as substitution, only that checking length is just one character.
