### ISSUE TITLE
support hexadecimal floats

### ISSUE THREAD

**Issue by Artoria2e5** [Lellansin/node-scanf#24]
Hexadecimal float literals are defined in ISO C99 and ISO C++17. They are of the form (case-insensitive):
```
hex_digit = [0-9a-f]
hexponent = p [+-]? hex_digit+
heximal = "." hex_digit*
hex_float = "0x" hex_digit+ heximal? hexponent?
```

C++ `scanf` and friends take it in the `a` format, although truth be told the most popular library glibc takes it in the usual `f` too. A function to parse it is:

```typescript
// this is just the grammar plus a sign
const hexf = /^([+-]?)0x([0-9a-f]+)(\.[0-9a-f]*)?(p[+-]?[0-9a-f]+)?/i
function parseHexFloat(s) {
  const res = s.match(hexf)
  if (res === null) return null
  let [_, sign, sint, spoint, sexp] = res
  // We glue the integer and point parts together when parsing
  const integer = parseInt(sign + sint + (spoint !== undefined ? spoint.slice(1) : ''), 16)
  // The actual exponent is the specified exponent minus the de..heximal points we shifted away
  const exponent = parseInt(sexp.slice(1), 16) - 4 * (spoint !== undefined ? spoint.length - 1 : 0)
  return integer * 2**exponent
}
```

There are, of course, obvious concerns with this method. One of them is the existence of people who simply adds a lot of zeros to blow up the parseInt part above MAX_SAFE_INTEGER, at which point it still tries to work but is no longer precise. One thing we can do is to yank away the extra zeros, which sounds slow. Alternatively, we can just chop the whole thing down to 13 hex characters! I mean, Number (IEEE 754 double) only has 52 bits of precision anyways... (We can obviously just forget about it. Only bad people mess HEX FLOATS up anyways.)

https://en.cppreference.com/w/cpp/language/floating_literal gives a nice explanation of the thing.

**Comment by Lellansin** [comment]
Hi @Artoria2e5 , due to the current implementation, the easiest way to support it is `%a` format, which you can check it in #25.
