### ISSUE TITLE
Impossibility to parse when we have this special caractere "|"

### ISSUE THREAD

**Issue by michwii** [Lellansin/node-scanf#3]
Hi,

This librairy is very interesting.

I'm trying to use it for parsing files.
Here is the row I'm trying to parse : 
|Server1|CTRL_SLA|Intranet|sla|2015-06-15 16:25:28|100

Therefore I wrote this command : 

var valuesExtracted = sscanf("|Server1|CTRL_SLA|Intranet|sla|2015-06-15 16:25:28|100", "|%s|%s|%s|sla|%s|%d");

Unfortunately, the result present in the variable valuesExtracted is [ undefined, '0', null, null, null ]

Is it due to the fact that I'm using a special caractere "|" as a separator ?

In the documentation examples, the separator is a blank space.

Thank you for your help.

**Comment by Lellansin** [comment]
Hi @michwii, Glad to meet you. I'v fix this at https://github.com/Lellansin/node-scanf/commit/95ef2a2ce136d5d1452fc2aa78bac925cca90e29.

**Comment by michwii** [comment]
Hi Lellansin, thank you very much for your answer =D

I wish you a good day !

Very nice work by the way ;)
