### ISSUE TITLE
How to solve Chinese encoding fault？

### ISSUE THREAD

**Issue by lhlybly** [Lellansin/node-scanf#9]
![image](https://cloud.githubusercontent.com/assets/9162319/22012611/eb55e71a-dccf-11e6-9efb-c1bb54cf94c9.png)
我输入的中文字符用node保存到本地文件就变成这样了。

**Comment by Lellansin** [comment]
Hi, sorry for reply later. Please specify the error case, like the screenshot below.

![image](https://user-images.githubusercontent.com/2081487/31753814-9b86b4c4-b458-11e7-9465-1dc41f342c5f.png)

**Comment by Lellansin** [comment]
Temporarily close, feel free to reopen.
